### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by mastercho25** [shortdudey123/chef-salt#5]
Please forgive me if I have misread the code and some of these are not correct.

Regarding the following in the documentation under Minion: "node['salt']['minion']['environment'] - The environment in which to search for a master; or nil to search all environments (defaults to the node's environment)"
    1) Was this supposed to be node['salt']['master']['environment']?  The documentation Master section refers to node['salt']['minion']['environment'] which seems to be right if I am interpreting the intent correctly.
    2) The code appears to be using node.salt['minion']['master_environment'] to search for master(s).  which isn't either of the above..  It seems like it should be using node.salt['master']['environment'] to me.
    3) The code doesn't appear to handle the case of it being null as advertised in the documentation.
    4) The code doesn't appear to handle the default case as advertised in the documentation.
    5) The code does refer to this attribute when the value is "_default", but that is not documented anywhere.

Regarding the corresponding Documentation under Master:
    6) The master recipe code appears to be using node.salt['master']['environment'] to look for minions.  Should that be node.salt['minion']['environment'] as documented?
    7) Same as #3 above
    8) Same as #4 above

Thank you for your cookbook, and thank you for considering my comments.

**Comment by shortdudey123** [comment]
cookbook has changed a bit since this issue was opened
Please create a new issue if there is any further questions
